[project]
name = "k6-mcp-server"
version = "0.1.0"
description = "Model context protocol server for k6 load testing"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.6.0",
]